import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './assets/components/Navbar'
import Cursor from '@/app/assets/components/Cursor/Cursor'
import styles from '@/app/assets/components/style.module.scss'
import Info from './assets/components/information/Info'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={styles.html + " relative"}>
      <Navbar />
      <Cursor />
      <body className={inter.className + " body"}>{children}</body>
    </html>
  )
}
